### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [wdehaes/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by wdehaes** [comment]
Hi,

Thanks for the feedback. I included the mobile meta tag and also the css for IE10 (didn't get a chance to test that last one yet). I checked it on my phone and it looks better now.

**Comment by BillyMassey** [comment]
Good Job!
